# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'frontend' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for frontend

  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'

  target 'frontendTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'frontend-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for frontend-tvOS

  target 'frontend-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
